version: '3.8'

services:

  strapi-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: conectaelas
    container_name: ConectaElas
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=conectaelas
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root
      - HOST=0.0.0.0
      - PORT=1338
      - JWT_SECRET=ZlpG7CxK5+VLz+ydOoJ8sA==
    ports:
      - '1338:1338'
    depends_on:
      - db
    command: npm run start  # Roda em modo de produção

  # Serviço do banco de dados
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: conectaelas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
